apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: image-updater
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: test-application
      annotations:
        argocd-image-updater.argoproj.io/image-list: resnostyle/image-updater
        argocd-image-updater.argoproj.io/write-back-method: git
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      source:
        path: deployment
        repoURL: git@github.com:resnostyle/argo-image-updater.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
