apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argo-cd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: test-application
      argocd-image-updater.argoproj.io/image-list: nginx
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      source:
        path: deployment
        repoURL: git@github.com:resnostyle/argo-image-updater.git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
